### ISSUE TITLE
Pocket: Hypothesis 1 Opportunity Prototypes

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx-planning-and-intake#11]
### Proposed project plan

**Goal**

-android mobile prototypes to test Hypothesis 1 and first area of exploration: 
**Hypothesis** It’s challenging for users to find the content they want to consume when they open Pocket today.  **Area of exploration:** Make it easy for users to find content of a certain type without needing to manually organize it (Pocket organizes the content for them). 

 ... 

**Subtasks**
- [x] Connect with Laurie + mobile team to review research and initial concepts
- [x] High fidelity card examples
- [x] Figma prototype Search + Filters at the top of My List
- [x] Figma prototype Start in Filters
- [x] Awaiting final review from Pocket Team

**Timeline and priority (if applicable)**
- Exploration of artwork files and establishing patterns - 1 day
- Production of card visual examples for team review Monday ( Monday Oct 5 )
- Production of prototype (Thursday Oct 8)
- All prototypes delivered on October 13

**Additional context**

- Slide #18 in [Pocket Mobile: 9/17](https://docs.google.com/presentation/d/1QLLEDadRyEQOw7B3r6QhOgxA1rh1Z2u4PgOh_e1h3Lw/edit?usp=sharing)
**- project figma**: https://www.figma.com/file/82GcVMINz0flufVzFIl4Sa/My-List?node-id=35%3A0
**android design library:** https://www.figma.com/file/Ws0xnnKtmiQ1DSD8HAR3XH/Mobile-Components-and-Guidelines-Proposal?node-id=0%3A1
**android discover**https://www.figma.com/file/K70GjbldhXypBlshbeciA0/Android-Discover?node-id=2841%3A11563

**Comment by malqinneh** [comment]
@lduggins855 adding Slack message to Laurie for transparency:

> Due to resourcing constraints; we're limited to the number of issues we can work on this week. This issue will be prioritized on Monday (Sep 28).

**Comment by mcroud** [comment]
Began working on production of first prototpye

**Comment by mcroud** [comment]
Card design suggestions shared with Laurie for critique: 
https://www.figma.com/file/82GcVMINz0flufVzFIl4Sa/Mobile-My-List?node-id=401%3A0

**Comment by mcroud** [comment]
Video demo of the prototype for hypothesis 1 was shared with the team yesterday. Currently implementing suggestions and feedback.

**Comment by mcroud** [comment]
All 4 prototypes are complete and in Figma for final review and feedback.

**Comment by malqinneh** [comment]
@lduggins855 Hey Laurie! Any updates on this issue? Is testing going well?

**Comment by lduggins855** [comment]
we will be testing these next week! but the work on the prototypes is all done. should i move this to "closed?"

**Comment by malqinneh** [comment]
Thank you! I'll do that :)
