### ISSUE TITLE
Exploration of New Markets

### ISSUE THREAD

**Issue by reganMoz** [mozilla/dpx-planning-and-intake#168]
## Explore potential business models for Hubs product and make recommendations to grow our audience beyond our initial community of gamers, 3D creators and early adopters

- [ ] Experimentation, testing, and validation for consumer subscription model
- [ ] Propose at least one(1) alternative business model option (i.e. co-development agreements, partnerships, revenue sharing)
- [ ] Market/competitor analysis to define value proposition
- [ ] Create, refine, implement and document a pipeline for Hubs at least one(1) new concept exploration by H1
- [ ] Document two(2) previously proposed concepts by Q1
- [ ] Research, biz analysis and document any value proposition for hubs in Headsets by EOY
