### ISSUE TITLE
Current Product

### ISSUE THREAD

**Issue by reganMoz** [mozilla/dpx-planning-and-intake#170]
## Enable product team to set priority of work based on informed design decisions by bringing robust user-centric design recommendations that boost product satisfaction, address product stability, and enhance usability

- [ ] Set a standard of process to communicate recommendations to the product team, weekly strategy meetings by Q1
- [ ] Document recommendations and chosen actions or next steps by Q1
- [ ] Track percentage of recommendations advised / implementation by H1
- [ ] Set a standard of process for UX testing the live app, creating a permanent feedback loop for product enhancements by Q1
- [ ] Track number of tasks, tests, problems discovered, solutions proposed
- [ ] Address product gaps for Hubs Cloud based on feedback from existing customers
- [ ] Holistic design review of entire product to document design gaps or issues
- [ ] Track metrics (as discussed and agreed upon by team by Q1) to attain baseline by Q2 of customer satisfaction of product; improve metric by EOY
- [ ] User trust kit completed for Hubs
- [ ] Report on gaps from user trust kit findings reported to key stakeholders including design lead, product manager(s), eng
