### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by reganMoz** [mozilla/dpx-planning-and-intake#184]
### Establish the design team as the go to resource for communicating new features, design ideas, enhancements with the Hubs community

- [ ] Establish a Design channel on discord by Q1
- [ ] Set up a bi-weekly design meetup with the community for feedback by Q1
- [ ] Build a template for "Feedback Posts" design newsletter by Q1
- [ ] Post design newsletter for feedback at least twelve(12) issues by EOY
- [ ] Identify and document owners of each form of communication channel by Q1
- [ ] Institute weekly communication sync meetings by Q1
- [ ] Document all channels, owners, and activities by Q1
- [ ] Promote forms of communication channels by H1
- [ ] Track number of active members in each community channel by H1
