### ISSUE TITLE
Pocket Prototype Exploration: Video Transcription and Narration

### ISSUE THREAD

**Issue by heaversm** [mozilla/dpx-planning-and-intake#239]
### Proposed project plan

**Goal**
To explore the possibilities of extracting greater utility and accessibility from videos parsed in Pocket articles by obtaining their transcripts via the youtube transcription API.

**Subtasks**
List all action items or subtasks to accomplish the above goal.

- [ ] Prototype retrieval of a transcript via Youtube
- [ ] Add the ability to translate the transcript into a user specified language
- [ ] Test ability to authenticate to the pocket developer API
- [ ] Test retrieval of a limited subset of articles containing videos
- [ ] Identify videos within this subset that are youtube specific
- [ ] Combine the Youtube and Pocket API functionality into one backend service
- [ ] Given a user-selected video transcript, connect to a TTS service (Pocket currently uses Polly...we think) and narrate the transcript
- [ ] Explore the ability to connect this article transcript retrieval and narration to a smart device (e.g. Alexa)

**Timeline and priority**
Rough timeline based on a 5-day sprint.

- [ ] Mon, March 15 - transcription functionality
- [ ] Mon, March 22 - narration functionality
- [ ] Mon, March 29 - smart device functionality

**Linked issues (if applicable)**
Please list any other GitHub issues that are constrained by or dependent on this feature here.

- [Title](link)

**Additional context**
Forthcoming
- [Title](link)
