### ISSUE TITLE
S&P segment visuals

### ISSUE THREAD

**Issue by fernzharp** [mozilla/dpx-planning-and-intake#24]
### Proposed project plan

**Goal**
We need a good way to articulate our security & privacy target users in a visual format

**Subtasks**

- [x] Sync with Heather and Gloria to identify and align on deliverables.
- [x] First iteration of images that communicate our security & privacy target users and what they do
- [x] Share first iteration with DPX-XD/Heather and Gloria
- [x] Refine/revise after first round feedback 
- [x] Add, texture and stylisation

**Timeline and priority**
Rough timeline based on a 5-day sprint.

- [x] Share first iteration of images- 6 images for target users/7 of what they do/Group image by EOD Monday 10/26/2020.

- [x] Share second iteration of images by EOD Tuesday 10/27/2020.

- [x] By Friday, October 30

**Additional context**

- [Party people exec summary](https://drive.google.com/file/d/1YI24-te-uYfS_7AsDnPUSQDTPU-keNhi/view)
- [P&S Segment visuals](https://docs.google.com/document/d/1wTM_rGkGS9yVJ-sv0Zk9ztJwSZxtzf6kthSbN6iY13A/edit)
- [Forrester segment descriptions](https://go.forrester.com/blogs/the-data-digest-forresters-consumer-privacy-segmentation/)

**Comment by fernzharp** [comment]
Update: I met with Heather and Gloria today to identify and align on deliverables. 
Beginning some strategy and ideation today and will sync again Monday 10/26/2020.

**Comment by fernzharp** [comment]
Update: Completed first ideation of 6 segment visuals, 7 of what they do and a combined image title page.
I'll share in DPX-XD slack chat and with Heather and Gloria.

Note: These are a WIP and will be refined further!

![Frame 1.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/abec3288-d95e-4383-9450-8caec5637389)![Frame 2.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/b6013882-9dee-46b6-85a5-faea0e390dbb)

**Comment by fernzharp** [comment]
Update: Completed revisions after positive feedback on first concepts. Sent to Heather and DPX-XD and will wait for more feedback before proceeding.
![Frame 4.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/85ee0d79-4766-4b05-bd33-6cb751fe36af)
![Frame 5.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/82d6947b-d31c-4959-bee3-7c266d76fdcf)

**Comment by fernzharp** [comment]
Update: Revised concepts based on Heather's feedback, awaiting further instruction.
![Frame 6.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/a2e9b3cc-138e-4a27-9943-0879ece36b76)

**Comment by fernzharp** [comment]
Update: Waiting for Gloria to return from PTO Monday 11/02/2020 to give feedback. Will make the work available for critique by the DPX org next week after Gloria reviews.

Latest images:
Data savvy digital moves to Nervous unaware.
Nervous unaware to skeptical protectionist.
Skeptical protectionist to data savvy digital.


![Frame 6.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/91729c5d-06a5-428e-a010-7c46f6c97927)
![Frame 7.png](https://images.zenhubusercontent.com/5f691a47ee469c25e860480a/af8c9cd4-353e-47bc-b444-b46c8ff877b4)
