### ISSUE TITLE
VPN: v2.0 Cross Platform UX/UI

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx-planning-and-intake#25]
### Proposed project plan

**Goal**
- Ensure that the Mac OS and Linux VPN applications have all necessary assets for public release
- Ensure that the Mac OS and Linux VPN applications have all necessary menu items for public release

**Subtasks**

List of UI assets

- [x] Dock icon (Mac OS [ICNS](https://drive.google.com/drive/folders/1Yb4eFLV1O4x0N_0qnaYQUYeUg4fTlLxh?usp=sharing), [PNG](https://drive.google.com/drive/folders/1Gmc_uduJXPsSI6iWWakeMmmmkuudKTLa?usp=sharing), Linux [PNG](https://drive.google.com/drive/folders/1Yb00uBQCSq2ZKfqOsV2o5l2Sga1wSPaN?usp=sharing))
- [x] Menu bar icon(s) (Mac OS, Linux)
- [x] Push notifications icon (Mac OS, Linux)
- [x] Onboarding screen(s) (iOS, Android) / Replace WIP “quick access” icon

List of UX items

- [x] Dock icon menu list
- [x] Menu bar icon menu list
- [x] Push notifications copy and action items (Connecting, Connected, Disconnected, Captive portal detection)

**Timeline and priority**

Timeline based on a 5-day sprint:

- [x] Monday, October 26: Dock icons for Mac OS and Linux
- [x] Monday, October 26: Menu bar icon(s) for Mac OS and Linux
- [x] Tuesday, October 27: Push notification icon(s) for Mac OS and Linux
- [x] Tuesday, October 27: Push notifications copy and action items for Mac OS and Linux
- [x] Wednesday, October 28: Onboarding screen(s) / Replace WIP "quick access" graphic

**Additional context**

- [📝 VPN v2.0 Cross Platform UX/UI](https://docs.google.com/document/d/1RSGPlxaWKSw-6IE24PlirGuACobRsxbmuQJPap27Ld0/edit?usp=sharing)
- [🎨 VPN Mac OS Notifications - Figma](https://www.figma.com/file/OJvazBg05cCIKvaLQkPWdv/Notifications)
- [🎨 VPN Mac OS Doc Icons - Figma](https://www.figma.com/file/zUJnmB9v2ZNOlh5oVd7lMF/Dock-Icons)
- [🎨 VPN Linux Doc Icons - Figma](https://www.figma.com/file/COmhUpSznZjUlBiB5OJCJS/Dock-Icons)
- [🎨 VPN Mac OS/Linux Menu Bar Icons/States - Figma](https://www.figma.com/file/DQOy6IMHbKylNmvirxh2Ia/Menu-Bar-Icons)

**Comment by malqinneh** [comment]
![Mac OS - Notification.jpg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/3ed43848-d2d8-4d91-bff5-654c12c158ed)
![Mac OS - Menu Bar.jpg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/0bb03ecd-0584-49f2-9376-9e6fd2f58370)
![WIP SVG.svg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/353429a7-2267-4ac4-ac45-f2ceb055cbf3)
