### ISSUE TITLE
Monitor - Family Monitoring UX Exploration

### ISSUE THREAD

**Issue by heaversm** [mozilla/dpx-planning-and-intake#26]
### Proposed project plan

**Goal**
Briefly explain the problem, goal(s) or outcome(s) you would like to achieve.

The Monitor team wants to incorporate the concept of Family Monitoring - adding family members to the list of monitored accounts. The goal of this UX Exploration is to evolve the initial design exploration work, [found here](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/blurts-server/1965) (#1965), in order to further assess and design for the implications this concept has on the overall user experience within monitor

**Subtasks**
List all action items or subtasks to accomplish the above goal.

- [ ] Scope out timeline, deliverables, and priorities in conjunction with Privacy team.
- [ ] Review and incorporate feedback from [this document](https://docs.google.com/presentation/d/1QQaEsUIeDFDWbphjxv0PXcSfQSiJN-Gl_-qQX7CSUw8/edit#slide=id.g9ef87241c5_0_37)
- [ ] Analyze existing research and strategy to see how this might influence messaging around family monitoring.
- [ ] Work with @groovecoder to iterate on an MVP of this concept.

**Timeline and priority**
Rough timeline based on a 5-day sprint.

Need to work with Privacy team to identify timeline / deliverables. Estimate 1-2 days to iterate on designs based on latest feedback. Perhaps 1 additional day to analyze existing strategy / research.

**Linked issues (if applicable)**
#1965 - [Start a concept Flow for "Add A Family Member"](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/blurts-server/1965)

**Additional context**

[Figma files can be found here](https://www.figma.com/file/sJhXA6pgckz3b4xEnrxp6K/Family-Sign-Up). All additional context can be found in the above linked issue #1965. Contacts within Privacy are Luke Crouch and Ted Schuh.

**Comment by malqinneh** [comment]
@isobelroe Gloria is the researcher on S&P - she will be able to support usability testing.

**Comment by heaversm** [comment]
More potentially applicable research:

[P/S for Adolescents to Elders](https://docs.google.com/presentation/d/1s4Fa2IhInWWtSMVkaGhLKH_ihIgbcIJtc_PV3w4R7KU/edit#slide=id.g9438479dc1_0_9)

**Comment by heaversm** [comment]
Work In-Progress MVP Implementation being formulated in [this doc](https://docs.google.com/presentation/d/1XtOGKpKDY3q3gViyptsPv_zpGAUcnlXwkuZ64WYxALA/edit#slide=id.ga6eb61ea5e_0_169).

**Comment by heaversm** [comment]
All feedback from the wireframes above has been incorporated into a Figma prototype, which we will work on getting to a testable state in a separate issue. I believe this issue can be closed.
