### ISSUE TITLE
Finalize family monitoring MVP

### ISSUE THREAD

**Issue by heaversm** [mozilla/dpx-planning-and-intake#29]
### Proposed project plan

**Goal**

Create a testable Figma prototype that incorporates all of the feedback from S&P on the Family Monitoring concept

**Subtasks**
List all action items or subtasks to accomplish the above goal.

- [x] Create clickable Figma prototype that allows a user to walk through the process of adding family members to Monitor.

- [ ] Address any S&P feedback raised through the interactive prototype

**Timeline and priority**
Rough timeline based on a 5-day sprint.

- [x] Monday, 11/9/2020 - incorporate current feedback into Figma prototype and run by Luke / Ted
- [x] Tuesday, 11/10/2020 - make sure there are no further changes requested by S&P.

**Linked issues (if applicable)**
#26, #1965

**Additional context**

[Wireframes](https://docs.google.com/presentation/d/1XtOGKpKDY3q3gViyptsPv_zpGAUcnlXwkuZ64WYxALA/edit?ts=5fa964fd#slide=id.g9ef87241c5_0_37) for the concept can be found here.

Current state of Figma prototype is [outlined here](https://mozilla.slack.com/files/U01DXV34LAC/F01E7PMR4HY/family-monitor-mvp-1_3.mp4?origin_team=T027LFU12&origin_channel=D01D0HW21QF) and will be posted in dpx-critique

**Comment by heaversm** [comment]
[WIP Testing Plan can be found here](https://docs.google.com/document/d/1GYuxX4c24vAlobsCiNHLNJnLnmxEu9qfQzYqIDcLt5M/edit?usp=sharing)

[Figma Prototype Walkthrough Here](https://drive.google.com/file/d/1Ga-u7bsO1faMmnlNt4t5bEr9TnodrrHt/view?usp=sharing)

**Comment by heaversm** [comment]
In working with Gloria we identified an opportunity to split this prototype into two separate prototypes for Dyad testing (1 for the primary account holder, one for the family member). As a result we will continue to iterate on the MVP via the following two prototypes:

[Primary Account Holder Experience](https://www.figma.com/file/BJBb1GRtUhdWQSDfRMBnr3/Family-Monitor-Primary?node-id=0%3A1)
[Family Member Experience](https://www.figma.com/file/VUBFQlvEY2llu7MNVqjX9C/Family-Monitor-Secondary?node-id=0%3A1)

**Comment by heaversm** [comment]
This work has been put on hold. Going to close this ticket.
