### ISSUE TITLE
Prepare Family Monitoring prototype for testing

### ISSUE THREAD

**Issue by heaversm** [mozilla/dpx-planning-and-intake#30]
### Proposed project plan

**Goal**

Get the Family Monitoring prototype into testing

**Subtasks**
List all action items or subtasks to accomplish the above goal.

- [x] Run Family Monitor MVP past Product Integrity
- [ ] Develop a testing plan with Heather / Gloria
- [ ] Ensure all S&P objectives for the prototype are addressed

**Linked issues (if applicable)**

- [Finalize Family Monitor MVP](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/dpx-planning-and-intake/29)

See DPX Critique Slack channel for ongoing prototype status.

**Comment by heaversm** [comment]
Spoke with Nicole S about the Family Monitor concept from a PI perspective. She is going to circle back with @malqinneh  and Heather. While there were no immediate red flags per se, there is an overall question as to whether Monitor fits within the Prospector / Family CTO concept, or whether that initiative should be focused on new offerings rather than shoe-horning existing products into it.

This meeting was followed with an S&P check-in, which raised additional questions:

* How do we treat resolved breaches - the fact that a family monitor may be resolving an individuals' breaches could raise concerns. 
* Is it appropriate to test this concept now, or should there be a more primary testing phase which is a bit more conceptual / qualitative: "is this a feature you would be interested in? what are your concerns?" etc.
* should there be more granularity as to the buckets into which monitored accounts fall into (currently just "family", "personal", "primary".

Heather mentioned that some research and testing conducted next week should provide some answers that might be beneficial to determining the viability of the Family Monitor concept.

It was also pointed out that all of this breach data is publicly accessible already, therefore the measures being taken in this implementation to outline concerns might be introducing undue complexity and caution into an otherwise fairly streamlined service.

**Comment by heaversm** [comment]
[A testing plan is being developed here](https://docs.google.com/document/d/1GYuxX4c24vAlobsCiNHLNJnLnmxEu9qfQzYqIDcLt5M/edit#heading=h.sd3nt9705rhy) in conjunction with Gloria, Heather, Ted, and Luke.

**Comment by heaversm** [comment]
This work has been put on hold. Closing.
