### ISSUE TITLE
Obtain Family Monitor Legal Sign-Off

### ISSUE THREAD

**Issue by heaversm** [mozilla/dpx-planning-and-intake#49]
### Proposed project plan

**Goal**
The Family Monitor concept has been presented to Legal, who have surfaced aspects of the concept that need clarification, have specific legal requirements, need more specific language, etc. to be deemed implementable in the existing Monitor experience.

[These requests can be found in this document] (https://docs.google.com/document/d/10AuCSYICTHSV17HsI4LHMO6l1Sgw37jtEPUclqg8meY/edit?userstoinvite=jclaudius%40mozilla.com&ts=5fb43107&actionButton=1#)

**Subtasks**

- [ ] Address legal concerns within the prototype
- [ ] Answer any technical questions

**Timeline and priority**

- [ ] Mid December 2020: Provided all concerns are addressed, legal should be able to sign-off on the concept.

**Linked issues (if applicable)**

[Finalize MVP](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/dpx-planning-and-intake/29)

[Prepare MVP for Testing](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/dpx-planning-and-intake/30)

**Comment by heaversm** [comment]
This work has been put on hold. Closing.
