### ISSUE TITLE
VPN: Prioritize list of market features

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx-planning-and-intake#5]
**Request**

Prioritize [list of market features](https://docs.google.com/spreadsheets/d/10icwjDzZ0-ohfjSSRF_0auYvUmyY3uaLziUTjEWVVEE/edit#gid=4608378) to be integrated with Mozilla VPN (prioritization based high impact)
- [ ] Clarify and verify the scoring/ order of priority of features (e.g. scoring in the market features sheet)
- [ ] Clarify the scope of features (e.g. what does a kill switch entail)
- [ ] Clarify the required XD support (screens, brand, user flows)

**Timeline and priority (if applicable)**

- 9/16: DPX mid-sprint review of progress
- By 9/18 (or earlier): DPX + S&P review and next steps 
- Release all v1.1 features within 6 weeks (late Oct)

**Linked issues**

- [VPN: Prioritize experience features and clarify overall value proposition](https://app.zenhub.com/workspaces/experience-design-5f58057dfb3d02001259cefb/issues/mozilla/dpx-design-process/6)

**Additional context**

- [List of market features](https://docs.google.com/spreadsheets/d/10icwjDzZ0-ohfjSSRF_0auYvUmyY3uaLziUTjEWVVEE/edit#gid=4608378) from the S&P team
- VPN 1.1 [scope of work document](https://docs.google.com/document/d/1Q2db37zgvJpTDM6awE8jSBledEiM8TzJryZXd3zeuDs/edit?usp=sharing)

**Comment by malqinneh** [comment]
Emilie's [process doc](https://docs.google.com/document/d/1WEv4GOvN-3kxXkEIC_8gJ7Fhr-dzcE8UlQ6aHmvNAVU/edit?usp=sharing)

**Comment by phirework** [comment]
I've asked for permission to the process doc, can you share it @malqinneh?

**Comment by malqinneh** [comment]
Which process doc? I just checked and you should have access to the two documents linked under [Additional context]. Let me know!

FYI, this issue along with #6 is picked up by Mimi.

**Comment by phirework** [comment]
@malqinneh Mimi's process doc.

**Comment by malqinneh** [comment]
@emiliebadin Jenny is our team lead and overlooks projects -- especially helpful from a feasibility perspective. She can help with assessing technical constraints with the engineers (re: timeline). If you share your process doc (when it's ready), she can look into proposed scope of work and timeline.

**Comment by malqinneh** [comment]
@emiliebadin can you please update the subtasks and timeline in the description to reflect this week? Thank you!

**Comment by emiliebadin** [comment]
Hi Mustafa,

Last Friday, I updated the issue that you created, and added more items to the list. Did you see the changes?

**Comment by malqinneh** [comment]
Yes! I saw the changes to the [list of experience features issue](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/dpx-planning-and-intake/6). Anything we need to update with this issue about the list of market features? Or is this redundant now/should be closed?
