### ISSUE TITLE
VPN: List of experience features and clarify overall value proposition

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx-planning-and-intake#6]
**Request**

Prioritize experience features and clarify overall value proposition
Includes but not limited to:

- [x] 2.0 Goal (Adam's key result)
- [x] 2.0 Strategies: Adoption, Traction, Retention, Visibility
- [x] Review of [Features List](https://docs.google.com/spreadsheets/d/10icwjDzZ0-ohfjSSRF_0auYvUmyY3uaLziUTjEWVVEE/edit#gid=0) proposed by PM
- [ ] Produce [User Stories](https://docs.google.com/spreadsheets/d/1VCT8LOru5b3bCm2k01-uJT4w48PY_zRKrs9NwYEK3w4/edit?ts=5f6127ee#gid=0) in collaboration with UR and PM
- [x] Investigation on [VPN Industry Standard Features] (https://docs.google.com/document/d/19KBSqJYR5AKEy5EAprc17e_kCZrA-m4p6ZkXZ3bJaTE/edit#)
- [ ] Collect UR data from Gloria to update PRD:
  - [ ] UR on VPN personas
  - [ ] UR on most wanted features
  - [ ] UR on retaining features
  - [ ] UR on subscription model
- [ ] FFx account / separate Mozilla-wide account(?)
- [x] Investigate ux conventions and design patterns that best support VPN experience
- [x] Explore design system and necessary changes for scalable product
- [ ] Noting and tabling important but not critical changes
- [ ] Create a work plan for both features + experience
- [ ] Align roadmap with 2.0 scopes
- [ ] [2.0 PRD agreement](https://docs.google.com/document/d/1gWXgeKxt-83gcSFPbCeO1iuJsmMAJpsVrCvMiFRDgLg/edit#) signed by team

**Timeline and priority (if applicable)**

- 9/16: DPX mid-sprint review of progress
- By 9/18 (or earlier): DPX + S&P review and next steps 
- By 9/25: (delivery will depend on how much time Gloria needs to complete UR)
- By 9/2: (PRD signed)

**Linked issues**

- [VPN: Prioritize list of market features](https://app.zenhub.com/workspaces/experience-design-5f58057dfb3d02001259cefb/issues/mozilla/dpx-design-process/5)

**Additional context**

- [List of market features](https://docs.google.com/spreadsheets/d/10icwjDzZ0-ohfjSSRF_0auYvUmyY3uaLziUTjEWVVEE/edit#gid=4608378) from the S&P team
- VPN 1.1 [scope of work document](https://docs.google.com/document/d/1Q2db37zgvJpTDM6awE8jSBledEiM8TzJryZXd3zeuDs/edit?usp=sharing)

**Comment by malqinneh** [comment]
Emilie's [process doc](https://docs.google.com/document/d/1WEv4GOvN-3kxXkEIC_8gJ7Fhr-dzcE8UlQ6aHmvNAVU/edit?usp=sharing)
