### ISSUE TITLE
Create Experience Strategy workspace in ZenHub

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx-planning-and-intake#9]
**Description**

Experience Strategy team wants to adopt ZenHub for their work. 

**Subtasks**

- [x] Set up a separate workspace in /dpx-design-process
- [x] Add new `xs` label
- [x] Invite XS team (list below)
- [x] Include the following columns: backlog, doing, blocked, done
- [ ] Ensure we can tag XS team within issues (for cross collaboration)

**Users to invite**

- Thomas: tlodato
- Megan: mbransn
- Laurie: lduggins855
- Wolasi:

**Comment by malqinneh** [comment]
@phirework still having issues tagging Thomas, Megan, and Laurie within issues. Can you try?
